// Code generated by protoc-gen-go.
// source: kairosdb_types.proto
// DO NOT EDIT!

package kairosdb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Represents a kairosdb datapoint
// https://github.com/kairosdb/kairosdb-client/blob/master/src/main/java/org/kairosdb/client/builder/DataPoint.java
type Datapoint struct {
	Timestamp int64   `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Value     float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
}

func (m *Datapoint) Reset()                    { *m = Datapoint{} }
func (m *Datapoint) String() string            { return proto.CompactTextString(m) }
func (*Datapoint) ProtoMessage()               {}
func (*Datapoint) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// Represents a sampling in the QueryMetrics request body
type Sampling struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Unit  string `protobuf:"bytes,2,opt,name=unit" json:"unit,omitempty"`
}

func (m *Sampling) Reset()                    { *m = Sampling{} }
func (m *Sampling) String() string            { return proto.CompactTextString(m) }
func (*Sampling) ProtoMessage()               {}
func (*Sampling) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

// Represents a kairosdb aggregator
// https://kairosdb.github.io/docs/build/html/restapi/Aggregators.html
type Aggregator struct {
	Name          string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	AlignSampling bool      `protobuf:"varint,2,opt,name=align_sampling,json=alignSampling" json:"align_sampling,omitempty"`
	Sampling      *Sampling `protobuf:"bytes,3,opt,name=sampling" json:"sampling,omitempty"`
}

func (m *Aggregator) Reset()                    { *m = Aggregator{} }
func (m *Aggregator) String() string            { return proto.CompactTextString(m) }
func (*Aggregator) ProtoMessage()               {}
func (*Aggregator) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Aggregator) GetSampling() *Sampling {
	if m != nil {
		return m.Sampling
	}
	return nil
}

// Represents the group_property in the request
// I've decided that it's not bad
type GroupBy struct {
	Name  string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Tags  []string          `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
	Group map[string]string `protobuf:"bytes,3,rep,name=group" json:"group,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GroupBy) Reset()                    { *m = GroupBy{} }
func (m *GroupBy) String() string            { return proto.CompactTextString(m) }
func (*GroupBy) ProtoMessage()               {}
func (*GroupBy) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GroupBy) GetGroup() map[string]string {
	if m != nil {
		return m.Group
	}
	return nil
}

// Reprents a kairosdb QueryMetric
// https://kairosdb.github.io/docs/build/html/restapi/QueryMetrics.html#id3
type QueryMetric struct {
	Name        string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Tags        map[string]*StringList `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GroupBy     []*GroupBy             `protobuf:"bytes,3,rep,name=group_by,json=groupBy" json:"group_by,omitempty"`
	Aggregators []*Aggregator          `protobuf:"bytes,4,rep,name=aggregators" json:"aggregators,omitempty"`
	Limit       int64                  `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
}

func (m *QueryMetric) Reset()                    { *m = QueryMetric{} }
func (m *QueryMetric) String() string            { return proto.CompactTextString(m) }
func (*QueryMetric) ProtoMessage()               {}
func (*QueryMetric) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *QueryMetric) GetTags() map[string]*StringList {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *QueryMetric) GetGroupBy() []*GroupBy {
	if m != nil {
		return m.GroupBy
	}
	return nil
}

func (m *QueryMetric) GetAggregators() []*Aggregator {
	if m != nil {
		return m.Aggregators
	}
	return nil
}

type Result struct {
	Name    string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	GroupBy []*GroupBy             `protobuf:"bytes,2,rep,name=group_by,json=groupBy" json:"group_by,omitempty"`
	Tags    map[string]*StringList `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Values  []*Datapoint           `protobuf:"bytes,4,rep,name=values" json:"values,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *Result) GetGroupBy() []*GroupBy {
	if m != nil {
		return m.GroupBy
	}
	return nil
}

func (m *Result) GetTags() map[string]*StringList {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Result) GetValues() []*Datapoint {
	if m != nil {
		return m.Values
	}
	return nil
}

// Represents a single set of results for a given Query
type Query struct {
	Results []*Result `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *Query) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

// Reprents a QueryMetrics request to kairosdb
// https://kairosdb.github.io/docs/build/html/restapi/QueryMetrics.html#query-properties
type QueryMetricsRequest struct {
	Metrics       []*QueryMetric `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
	CacheTime     int64          `protobuf:"varint,2,opt,name=cache_time,json=cacheTime" json:"cache_time,omitempty"`
	StartAbsolute int64          `protobuf:"varint,3,opt,name=start_absolute,json=startAbsolute" json:"start_absolute,omitempty"`
	EndAbsolute   int64          `protobuf:"varint,4,opt,name=end_absolute,json=endAbsolute" json:"end_absolute,omitempty"`
}

func (m *QueryMetricsRequest) Reset()                    { *m = QueryMetricsRequest{} }
func (m *QueryMetricsRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryMetricsRequest) ProtoMessage()               {}
func (*QueryMetricsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *QueryMetricsRequest) GetMetrics() []*QueryMetric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

// Represents response to kairosdb QueryMetrics request
type QueryMetricsResponse struct {
	Queries []*Query `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
	Errors  []string `protobuf:"bytes,5,rep,name=errors" json:"errors,omitempty"`
}

func (m *QueryMetricsResponse) Reset()                    { *m = QueryMetricsResponse{} }
func (m *QueryMetricsResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryMetricsResponse) ProtoMessage()               {}
func (*QueryMetricsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *QueryMetricsResponse) GetQueries() []*Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

type ListMetricNamesRequest struct {
}

func (m *ListMetricNamesRequest) Reset()                    { *m = ListMetricNamesRequest{} }
func (m *ListMetricNamesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListMetricNamesRequest) ProtoMessage()               {}
func (*ListMetricNamesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

type ListMetricNamesResponse struct {
	Results []string `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *ListMetricNamesResponse) Reset()                    { *m = ListMetricNamesResponse{} }
func (m *ListMetricNamesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListMetricNamesResponse) ProtoMessage()               {}
func (*ListMetricNamesResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

type ListTagNamesRequest struct {
}

func (m *ListTagNamesRequest) Reset()                    { *m = ListTagNamesRequest{} }
func (m *ListTagNamesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListTagNamesRequest) ProtoMessage()               {}
func (*ListTagNamesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

type ListTagNamesResponse struct {
	Results []string `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *ListTagNamesResponse) Reset()                    { *m = ListTagNamesResponse{} }
func (m *ListTagNamesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListTagNamesResponse) ProtoMessage()               {}
func (*ListTagNamesResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

type ListTagValuesRequest struct {
}

func (m *ListTagValuesRequest) Reset()                    { *m = ListTagValuesRequest{} }
func (m *ListTagValuesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListTagValuesRequest) ProtoMessage()               {}
func (*ListTagValuesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

type ListTagValuesResponse struct {
	Results []string `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *ListTagValuesResponse) Reset()                    { *m = ListTagValuesResponse{} }
func (m *ListTagValuesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListTagValuesResponse) ProtoMessage()               {}
func (*ListTagValuesResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

type HealthCheckRequest struct {
}

func (m *HealthCheckRequest) Reset()                    { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()               {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

type HealthCheckResponse struct {
	Healthy bool `protobuf:"varint,1,opt,name=healthy" json:"healthy,omitempty"`
}

func (m *HealthCheckResponse) Reset()                    { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()               {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

type HealthStatusRequest struct {
}

func (m *HealthStatusRequest) Reset()                    { *m = HealthStatusRequest{} }
func (m *HealthStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthStatusRequest) ProtoMessage()               {}
func (*HealthStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

type HealthStatusResponse struct {
	Results []string `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *HealthStatusResponse) Reset()                    { *m = HealthStatusResponse{} }
func (m *HealthStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthStatusResponse) ProtoMessage()               {}
func (*HealthStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func init() {
	proto.RegisterType((*Datapoint)(nil), "kairosdb.Datapoint")
	proto.RegisterType((*Sampling)(nil), "kairosdb.Sampling")
	proto.RegisterType((*Aggregator)(nil), "kairosdb.Aggregator")
	proto.RegisterType((*GroupBy)(nil), "kairosdb.GroupBy")
	proto.RegisterType((*QueryMetric)(nil), "kairosdb.QueryMetric")
	proto.RegisterType((*Result)(nil), "kairosdb.Result")
	proto.RegisterType((*Query)(nil), "kairosdb.Query")
	proto.RegisterType((*QueryMetricsRequest)(nil), "kairosdb.QueryMetricsRequest")
	proto.RegisterType((*QueryMetricsResponse)(nil), "kairosdb.QueryMetricsResponse")
	proto.RegisterType((*ListMetricNamesRequest)(nil), "kairosdb.ListMetricNamesRequest")
	proto.RegisterType((*ListMetricNamesResponse)(nil), "kairosdb.ListMetricNamesResponse")
	proto.RegisterType((*ListTagNamesRequest)(nil), "kairosdb.ListTagNamesRequest")
	proto.RegisterType((*ListTagNamesResponse)(nil), "kairosdb.ListTagNamesResponse")
	proto.RegisterType((*ListTagValuesRequest)(nil), "kairosdb.ListTagValuesRequest")
	proto.RegisterType((*ListTagValuesResponse)(nil), "kairosdb.ListTagValuesResponse")
	proto.RegisterType((*HealthCheckRequest)(nil), "kairosdb.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "kairosdb.HealthCheckResponse")
	proto.RegisterType((*HealthStatusRequest)(nil), "kairosdb.HealthStatusRequest")
	proto.RegisterType((*HealthStatusResponse)(nil), "kairosdb.HealthStatusResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for KairosDBClient service

type KairosDBClientClient interface {
	ListMetricNames(ctx context.Context, in *ListMetricNamesRequest, opts ...grpc.CallOption) (*ListMetricNamesResponse, error)
	ListTagNames(ctx context.Context, in *ListTagNamesRequest, opts ...grpc.CallOption) (*ListTagNamesResponse, error)
	ListTagValues(ctx context.Context, in *ListTagValuesRequest, opts ...grpc.CallOption) (*ListTagValuesResponse, error)
	QueryMetrics(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (*QueryMetricsResponse, error)
	HealthStatus(ctx context.Context, in *HealthStatusRequest, opts ...grpc.CallOption) (*HealthStatusResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type kairosDBClientClient struct {
	cc *grpc.ClientConn
}

func NewKairosDBClientClient(cc *grpc.ClientConn) KairosDBClientClient {
	return &kairosDBClientClient{cc}
}

func (c *kairosDBClientClient) ListMetricNames(ctx context.Context, in *ListMetricNamesRequest, opts ...grpc.CallOption) (*ListMetricNamesResponse, error) {
	out := new(ListMetricNamesResponse)
	err := grpc.Invoke(ctx, "/kairosdb.KairosDBClient/ListMetricNames", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kairosDBClientClient) ListTagNames(ctx context.Context, in *ListTagNamesRequest, opts ...grpc.CallOption) (*ListTagNamesResponse, error) {
	out := new(ListTagNamesResponse)
	err := grpc.Invoke(ctx, "/kairosdb.KairosDBClient/ListTagNames", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kairosDBClientClient) ListTagValues(ctx context.Context, in *ListTagValuesRequest, opts ...grpc.CallOption) (*ListTagValuesResponse, error) {
	out := new(ListTagValuesResponse)
	err := grpc.Invoke(ctx, "/kairosdb.KairosDBClient/ListTagValues", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kairosDBClientClient) QueryMetrics(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (*QueryMetricsResponse, error) {
	out := new(QueryMetricsResponse)
	err := grpc.Invoke(ctx, "/kairosdb.KairosDBClient/QueryMetrics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kairosDBClientClient) HealthStatus(ctx context.Context, in *HealthStatusRequest, opts ...grpc.CallOption) (*HealthStatusResponse, error) {
	out := new(HealthStatusResponse)
	err := grpc.Invoke(ctx, "/kairosdb.KairosDBClient/HealthStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kairosDBClientClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := grpc.Invoke(ctx, "/kairosdb.KairosDBClient/HealthCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KairosDBClient service

type KairosDBClientServer interface {
	ListMetricNames(context.Context, *ListMetricNamesRequest) (*ListMetricNamesResponse, error)
	ListTagNames(context.Context, *ListTagNamesRequest) (*ListTagNamesResponse, error)
	ListTagValues(context.Context, *ListTagValuesRequest) (*ListTagValuesResponse, error)
	QueryMetrics(context.Context, *QueryMetricsRequest) (*QueryMetricsResponse, error)
	HealthStatus(context.Context, *HealthStatusRequest) (*HealthStatusResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

func RegisterKairosDBClientServer(s *grpc.Server, srv KairosDBClientServer) {
	s.RegisterService(&_KairosDBClient_serviceDesc, srv)
}

func _KairosDBClient_ListMetricNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMetricNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairosDBClientServer).ListMetricNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kairosdb.KairosDBClient/ListMetricNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairosDBClientServer).ListMetricNames(ctx, req.(*ListMetricNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KairosDBClient_ListTagNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairosDBClientServer).ListTagNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kairosdb.KairosDBClient/ListTagNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairosDBClientServer).ListTagNames(ctx, req.(*ListTagNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KairosDBClient_ListTagValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairosDBClientServer).ListTagValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kairosdb.KairosDBClient/ListTagValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairosDBClientServer).ListTagValues(ctx, req.(*ListTagValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KairosDBClient_QueryMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairosDBClientServer).QueryMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kairosdb.KairosDBClient/QueryMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairosDBClientServer).QueryMetrics(ctx, req.(*QueryMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KairosDBClient_HealthStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairosDBClientServer).HealthStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kairosdb.KairosDBClient/HealthStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairosDBClientServer).HealthStatus(ctx, req.(*HealthStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KairosDBClient_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KairosDBClientServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kairosdb.KairosDBClient/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KairosDBClientServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KairosDBClient_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kairosdb.KairosDBClient",
	HandlerType: (*KairosDBClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMetricNames",
			Handler:    _KairosDBClient_ListMetricNames_Handler,
		},
		{
			MethodName: "ListTagNames",
			Handler:    _KairosDBClient_ListTagNames_Handler,
		},
		{
			MethodName: "ListTagValues",
			Handler:    _KairosDBClient_ListTagValues_Handler,
		},
		{
			MethodName: "QueryMetrics",
			Handler:    _KairosDBClient_QueryMetrics_Handler,
		},
		{
			MethodName: "HealthStatus",
			Handler:    _KairosDBClient_HealthStatus_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _KairosDBClient_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

func init() { proto.RegisterFile("kairosdb_types.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 789 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0x5b, 0x6f, 0xd3, 0x4a,
	0x10, 0x56, 0x92, 0xe6, 0x36, 0xe9, 0xed, 0x6c, 0xd2, 0x9e, 0xc8, 0x6a, 0x4f, 0x5b, 0x4b, 0x47,
	0x3a, 0x07, 0x50, 0x0a, 0x29, 0x42, 0x15, 0x2f, 0xa8, 0x17, 0x04, 0x02, 0x8a, 0x60, 0x5b, 0x55,
	0x82, 0x97, 0xc8, 0x49, 0x57, 0x8e, 0x55, 0xc7, 0x0e, 0xf6, 0x1a, 0x94, 0x5f, 0x83, 0xf8, 0x05,
	0xfc, 0x38, 0x24, 0x9e, 0x59, 0xef, 0xc5, 0xbb, 0x4e, 0x5c, 0xf2, 0xc2, 0x53, 0xed, 0xd9, 0x6f,
	0xbe, 0xf9, 0xe6, 0x9b, 0x59, 0x37, 0xd0, 0xb9, 0x75, 0xbc, 0x28, 0x8c, 0x6f, 0x86, 0x03, 0x3a,
	0x9b, 0x92, 0xb8, 0x37, 0x8d, 0x42, 0x1a, 0xa2, 0x86, 0x8a, 0x5a, 0x68, 0x4c, 0xfc, 0x29, 0x89,
	0xcc, 0x53, 0xfb, 0x19, 0x34, 0xcf, 0x1d, 0xea, 0x4c, 0x43, 0x2f, 0xa0, 0x68, 0x07, 0x9a, 0xd4,
	0x9b, 0x90, 0x98, 0x3a, 0x93, 0x69, 0xb7, 0xb4, 0x5f, 0xfa, 0xaf, 0x82, 0x75, 0x00, 0x75, 0xa0,
	0xfa, 0xd9, 0xf1, 0x13, 0xd2, 0x2d, 0xb3, 0x93, 0x12, 0x16, 0x2f, 0xf6, 0x63, 0x68, 0x5c, 0xb2,
	0x53, 0xdf, 0x0b, 0x5c, 0x8d, 0x48, 0x73, 0x9b, 0x12, 0x81, 0x10, 0xac, 0x24, 0x81, 0x47, 0x79,
	0x5a, 0x13, 0xf3, 0x67, 0xfb, 0x0b, 0xc0, 0x89, 0xeb, 0x46, 0xc4, 0x75, 0x68, 0x18, 0xa5, 0x88,
	0xc0, 0x99, 0xa8, 0x34, 0xfe, 0x8c, 0xfe, 0x85, 0x75, 0xc7, 0xf7, 0xdc, 0x60, 0x10, 0x4b, 0x76,
	0x9e, 0xdf, 0xc0, 0x6b, 0x3c, 0x9a, 0x95, 0xec, 0x41, 0x23, 0x03, 0x54, 0x18, 0xa0, 0xd5, 0x47,
	0x3d, 0xd5, 0x70, 0x4f, 0xa1, 0x70, 0x86, 0xb1, 0xbf, 0x96, 0xa0, 0xfe, 0x22, 0x0a, 0x93, 0xe9,
	0xe9, 0xac, 0xb0, 0x2c, 0x8b, 0x51, 0xc7, 0x8d, 0x59, 0xb1, 0x4a, 0x1a, 0x4b, 0x9f, 0x51, 0x1f,
	0xaa, 0x6e, 0x9a, 0xc2, 0x0a, 0x54, 0x58, 0x81, 0x1d, 0x5d, 0x40, 0x32, 0x89, 0xbf, 0xcf, 0x03,
	0x1a, 0xcd, 0xb0, 0x80, 0x5a, 0xc7, 0x00, 0x3a, 0x88, 0x36, 0xa1, 0x72, 0x4b, 0x66, 0xb2, 0x50,
	0xfa, 0x98, 0x37, 0x53, 0x59, 0xf5, 0xb4, 0x7c, 0x5c, 0xb2, 0xbf, 0x95, 0xa1, 0xf5, 0x3e, 0x21,
	0xd1, 0xec, 0x82, 0xd0, 0xc8, 0x1b, 0x15, 0xaa, 0x3c, 0x32, 0x54, 0xb6, 0xfa, 0x7b, 0x5a, 0x90,
	0x91, 0xd8, 0xbb, 0x62, 0x08, 0xa1, 0x49, 0xb4, 0xf1, 0x00, 0x1a, 0x5c, 0xdb, 0x60, 0x38, 0x93,
	0x9d, 0xfc, 0xb5, 0xd0, 0x09, 0xae, 0xbb, 0xd2, 0x9c, 0x27, 0xd0, 0x72, 0xb2, 0x09, 0xc5, 0xdd,
	0x15, 0x9e, 0xd0, 0xd1, 0x09, 0x7a, 0x7c, 0xd8, 0x04, 0xa6, 0x8d, 0xf9, 0xde, 0x84, 0x8d, 0xbb,
	0xca, 0xf7, 0x47, 0xbc, 0x58, 0x17, 0xd0, 0xcc, 0xe4, 0x14, 0xb8, 0x71, 0xcf, 0x74, 0x23, 0x57,
	0xe6, 0x92, 0xb5, 0x12, 0xb8, 0x6f, 0xbc, 0x98, 0x9a, 0x1e, 0xfd, 0x2c, 0x41, 0x0d, 0x93, 0x38,
	0xf1, 0x69, 0xa1, 0x3d, 0x66, 0xa7, 0xe5, 0xa5, 0x9d, 0xf6, 0xa4, 0x99, 0xc2, 0x13, 0x4b, 0x23,
	0x45, 0x85, 0x05, 0x1f, 0xef, 0x43, 0x8d, 0x2b, 0x51, 0xa6, 0xb4, 0x75, 0x46, 0x76, 0x95, 0xb0,
	0x84, 0xfc, 0xe9, 0xc6, 0x8f, 0xa0, 0xca, 0x47, 0xcc, 0x12, 0xeb, 0x11, 0x97, 0x17, 0x33, 0xba,
	0x54, 0xc5, 0xe6, 0xbc, 0x6e, 0xac, 0x00, 0xf6, 0xf7, 0x12, 0xb4, 0x8d, 0xc5, 0x88, 0x31, 0xf9,
	0xc4, 0xa4, 0x51, 0x74, 0x08, 0xf5, 0x89, 0x88, 0x48, 0x8e, 0xad, 0xc2, 0x45, 0xc2, 0x0a, 0x85,
	0x76, 0x01, 0x46, 0xce, 0x68, 0x4c, 0x06, 0xe9, 0x47, 0x81, 0x4b, 0x66, 0x1f, 0x08, 0x1e, 0xb9,
	0xf2, 0xc4, 0x95, 0x65, 0x5f, 0x8a, 0x88, 0x0e, 0x9c, 0x61, 0x1c, 0xfa, 0x09, 0x25, 0xfc, 0x46,
	0x56, 0xf0, 0x1a, 0x8f, 0x9e, 0xc8, 0x20, 0x3a, 0x80, 0x55, 0x12, 0xdc, 0x68, 0xd0, 0x0a, 0x07,
	0xb5, 0x58, 0x4c, 0x41, 0xec, 0x0f, 0xd0, 0xc9, 0x0b, 0x8e, 0xa7, 0x61, 0x10, 0x13, 0xf4, 0x3f,
	0xd4, 0x99, 0xf4, 0xc8, 0x23, 0x4a, 0xf1, 0xc6, 0x9c, 0x62, 0xac, 0xce, 0xd1, 0x36, 0xd4, 0x48,
	0x14, 0xa5, 0xab, 0x5b, 0xe5, 0x57, 0x59, 0xbe, 0xd9, 0x5d, 0xd8, 0x4e, 0x4d, 0x15, 0xcc, 0x6f,
	0xd9, 0xb6, 0x28, 0x3b, 0x98, 0xb7, 0x7f, 0x2f, 0x9c, 0xc8, 0xba, 0xdd, 0xbc, 0xdb, 0x4d, 0xed,
	0xed, 0x16, 0xb4, 0xd3, 0x24, 0x36, 0xe3, 0x1c, 0xd7, 0x43, 0xe8, 0xe4, 0xc3, 0x4b, 0x89, 0xb6,
	0xb3, 0x8c, 0x6b, 0xbe, 0x39, 0x8a, 0xe9, 0x11, 0x6c, 0xcd, 0xc5, 0x97, 0x52, 0x75, 0x00, 0xbd,
	0x24, 0x8e, 0x4f, 0xc7, 0x67, 0x63, 0x32, 0xba, 0x55, 0x44, 0x87, 0xd0, 0xce, 0x45, 0x35, 0xcd,
	0x98, 0x87, 0xc5, 0x5e, 0x36, 0xb0, 0x7a, 0x4d, 0x5b, 0x13, 0x09, 0x97, 0xd4, 0xa1, 0x89, 0xd9,
	0x5a, 0x3e, 0xbc, 0x4c, 0x4f, 0xff, 0x47, 0x05, 0xd6, 0x5f, 0xf3, 0x31, 0x9d, 0x9f, 0x9e, 0xf9,
	0x1e, 0x61, 0xff, 0x69, 0xae, 0x61, 0x63, 0xce, 0x6b, 0xb4, 0xaf, 0x47, 0x59, 0x3c, 0x20, 0xeb,
	0xe0, 0x37, 0x08, 0x29, 0xe2, 0x02, 0x56, 0x4d, 0xdf, 0xd1, 0x6e, 0x3e, 0x65, 0x6e, 0x4c, 0xd6,
	0x3f, 0x77, 0x1d, 0x4b, 0xba, 0x77, 0xb0, 0x96, 0x33, 0x1f, 0x2d, 0x26, 0xe4, 0xa6, 0x65, 0xed,
	0xdd, 0x79, 0xae, 0x05, 0x9a, 0x9b, 0x6d, 0x0a, 0x2c, 0xb8, 0xa2, 0xa6, 0xc0, 0xc2, 0x0b, 0xc1,
	0xe8, 0xcc, 0x61, 0x98, 0x74, 0x05, 0xb3, 0x33, 0xe9, 0x0a, 0x67, 0xf8, 0x0a, 0x5a, 0xc6, 0x8e,
	0xa0, 0x9d, 0x79, 0xb8, 0xb9, 0x50, 0xd6, 0xee, 0x1d, 0xa7, 0x82, 0xeb, 0x14, 0x3e, 0x66, 0xbf,
	0x3c, 0x86, 0x35, 0xfe, 0x63, 0xe3, 0xe8, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x71, 0x17, 0x5a,
	0xe5, 0xa2, 0x08, 0x00, 0x00,
}
